/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.59
 * Generated at: 2026-10-01 02:32:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.decorators;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1788407550200L));
    _jspx_dependants.put("jar:file:/C:/Users/Lenovo/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"vi\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title><sitemesh:write property='title'>Quản Trị Hệ Thống - WebVideo</sitemesh:write></title>\n");
      out.write("    <!-- Favicon -->\n");
      out.write("    <link rel=\"icon\" type=\"image/svg+xml\" href=\"data:image/svg+xml,&lt;svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'&gt;&lt;circle cx='50' cy='50' r='50' fill='%23ff4757'/&gt;&lt;polygon points='40,30 40,70 75,50' fill='%23ffffff'/&gt;&lt;/svg&gt;\">\n");
      out.write("    <!-- Bootstrap 5 CSS -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\n");
      out.write("    <!-- Admin Custom CSS -->\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            background-color: #f1f2f6;\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("        }\n");
      out.write("        .admin-navbar {\n");
      out.write("            background: #2f3542;\n");
      out.write("            box-shadow: 0 2px 10px rgba(0,0,0,0.15);\n");
      out.write("        }\n");
      out.write("        .sidebar {\n");
      out.write("            background: #2f3542;\n");
      out.write("            min-height: calc(100vh - 140px);\n");
      out.write("            color: #dfe4ea;\n");
      out.write("        }\n");
      out.write("        .sidebar .nav-link {\n");
      out.write("            color: #ced6e0;\n");
      out.write("            padding: 12px 18px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            margin: 4px 10px;\n");
      out.write("            transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("        .sidebar .nav-link:hover, .sidebar .nav-link.active {\n");
      out.write("            background: #ff4757;\n");
      out.write("            color: #ffffff;\n");
      out.write("        }\n");
      out.write("        .admin-content {\n");
      out.write("            flex: 1;\n");
      out.write("            padding: 25px;\n");
      out.write("        }\n");
      out.write("        .footer-custom {\n");
      out.write("            background: #1e272e;\n");
      out.write("            color: #d2dae2;\n");
      out.write("            padding: 20px 0;\n");
      out.write("            border-top: 3px solid #ff4757;\n");
      out.write("        }\n");
      out.write("        .footer-info {\n");
      out.write("            font-size: 1.05rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #f1f2f6;\n");
      out.write("        }\n");
      out.write("        .badge-exam {\n");
      out.write("            background: #ff4757;\n");
      out.write("            padding: 4px 10px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <sitemesh:write property='head'/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Admin Header -->\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark admin-navbar sticky-top\">\n");
      out.write("        <div class=\"container-fluid px-4\">\n");
      out.write("            <a class=\"navbar-brand fw-bold\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/videos\">\n");
      out.write("                <i class=\"fa-solid fa-shield-halved text-danger me-2\"></i>TRANG QUẢN TRỊ ADMIN\n");
      out.write("            </a>\n");
      out.write("            <div class=\"ms-auto d-flex align-items-center\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\" class=\"btn btn-outline-light btn-sm me-3\">\n");
      out.write("                    <i class=\"fa-solid fa-house me-1\"></i> Xem Trang Chủ\n");
      out.write("                </a>\n");
      out.write("                <span class=\"text-light me-3 d-none d-md-inline\">\n");
      out.write("                    Xin chào, <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account.fullname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("                </span>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"btn btn-danger btn-sm\">\n");
      out.write("                    <i class=\"fa-solid fa-right-from-bracket me-1\"></i> Đăng xuất\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Admin Layout with Sidebar -->\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <!-- Sidebar -->\n");
      out.write("            <nav class=\"col-md-3 col-lg-2 d-md-block sidebar py-3 collapse show\" id=\"sidebarMenu\">\n");
      out.write("                <div class=\"position-sticky\">\n");
      out.write("                    <div class=\"text-center mb-4 px-2\">\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.account.images ? 'https://picsum.photos/100' : sessionScope.account.images}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \n");
      out.write("                             class=\"rounded-circle border border-2 border-danger mb-2\" width=\"64\" height=\"64\" alt=\"admin\">\n");
      out.write("                        <h6 class=\"mb-0 text-white\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account.fullname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h6>\n");
      out.write("                        <span class=\"badge bg-danger mt-1\">Administrator</span>\n");
      out.write("                    </div>\n");
      out.write("                    <ul class=\"nav flex-column\">\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.servletPath eq '/admin/videos' or pageContext.request.servletPath eq '/admin/video/edit' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \n");
      out.write("                               href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/videos\">\n");
      out.write("                                <i class=\"fa-solid fa-video me-2\"></i> Quản lý Videos\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.servletPath eq '/admin/video/add' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \n");
      out.write("                               href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/video/add\">\n");
      out.write("                                <i class=\"fa-solid fa-plus-circle me-2\"></i> Thêm Video Mới\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.servletPath eq '/admin/orders' or pageContext.request.servletPath eq '/admin/order-detail' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \n");
      out.write("                               href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/orders\">\n");
      out.write("                                <i class=\"fa-solid fa-boxes-packing me-2\"></i> Quản lý Đơn hàng (COD)\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                        <hr class=\"text-secondary mx-3\">\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\">\n");
      out.write("                                <i class=\"fa-solid fa-globe me-2\"></i> Về Giao Diện Web\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("\n");
      out.write("            <!-- Main Content Area -->\n");
      out.write("            <main class=\"col-md-9 ms-sm-auto col-lg-10 admin-content\">\n");
      out.write("                <sitemesh:write property='body'/>\n");
      out.write("            </main>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Footer cố định theo Câu 1: Họ tên, MSSV, Mã đề -->\n");
      out.write("    <footer class=\"footer-custom mt-auto\">\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("            <div class=\"row align-items-center\">\n");
      out.write("                <div class=\"col-md-6 text-md-start mb-2 mb-md-0\">\n");
      out.write("                    <p class=\"footer-info mb-1\">\n");
      out.write("                        <i class=\"fa-solid fa-user-gear me-2 text-danger\"></i>\n");
      out.write("                        Họ tên: <strong>Trịnh Văn Phú Hào</strong> | MSSV: <strong>24110013</strong> | Mã đề: <strong>03</strong>\n");
      out.write("                    </p>\n");
      out.write("                    <small class=\"text-secondary\">Trang Quản Trị Hệ Thống | Môn Lập Trình Web (Jakarta EE + JPA + Tomcat 10)</small>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 text-md-end\">\n");
      out.write("                    <span class=\"badge-exam\">\n");
      out.write("                        <i class=\"fa-solid fa-code me-1\"></i> Mã đề: <strong>03</strong>\n");
      out.write("                    </span>\n");
      out.write("                    <span class=\"badge bg-secondary ms-2\">Admin Dashboard</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap 5 JS Bundle -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
